package org.linagora.linshare.auth.oidc;

import com.nimbusds.jwt.JWT;
import com.nimbusds.jwt.JWTParser;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.security.core.Authentication;

import java.text.ParseException;

// Only for researching purpose
class OIdcJwtAuthenticationProviderDebugTest {

	OidcAuthenticationTokenDetailsFactory oidcAuthenticationTokenDetailsFactoryMock = Mockito.mock(OidcAuthenticationTokenDetailsFactory.class);

//	private String issuerUrl = "https://login.microsoftonline.com/d6eca270-8f2c-4ae6-af9a-cb097502469a/v2.0";
	private String issuerUrl = "https://sts.windows.net/d6eca270-8f2c-4ae6-af9a-cb097502469a/";

	private OIdcJwtAuthenticationProvider subj =
			new OIdcJwtAuthenticationProvider(oidcAuthenticationTokenDetailsFactoryMock, issuerUrl, true);

	private String authToken = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IjYzUWUyQlNlZXM0MDhCcGpYMXJ1RlkySHUxUFcxdG1HaG9yLWVNVmw1NEkiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNmVjYTI3MC04ZjJjLTRhZTYtYWY5YS1jYjA5NzUwMjQ2OWEvIiwiaWF0IjoxNjc0NzMzNzkzLCJuYmYiOjE2NzQ3MzM3OTMsImV4cCI6MTY3NDczODExMSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhUQUFBQTBJS3JOa3hQeTFkdFN6Q3Q5MktWbjdGWUxUbkVRbVJmaTRGMitxTnloRC9CZWovMW85K2dTL245SjZqL0EwV1QiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkxpbnNoYXJlLWFwcCIsImFwcGlkIjoiNjY0MDk4MmMtNmRjOC00MTkzLWFkNzAtNzU1NjdmMjBjNWUzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJTaGVwaWxvdiIsImdpdmVuX25hbWUiOiJBbnRvbiIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjM3LjE3MS4yMDkuMjU1IiwibmFtZSI6IkFudG9uIFNoZXBpbG92Iiwib2lkIjoiZTE0NGVhNDMtMmFhZS00MzQ0LWE2YjAtMTllOTRkZjNkYjA5IiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMyMDAyNkM1RUFDQkUiLCJyaCI6IjAuQVU0QWNLTHMxaXlQNWtxdm1zc0pkUUpHbWdNQUFBQUFBQUFBd0FBQUFBQUFBQUNEQUZRLiIsInNjcCI6ImVtYWlsIG9wZW5pZCBwcm9maWxlIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiTUU3ZjFLZlNsVTd1Y1hwUWZFcFRnM3MtVEFnQUpzbGNlNDlXVkt4VVdHdyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBRiIsInRpZCI6ImQ2ZWNhMjcwLThmMmMtNGFlNi1hZjlhLWNiMDk3NTAyNDY5YSIsInVuaXF1ZV9uYW1lIjoiYW50b25Ad2JvdWRpY2hlbGluYWdvcmEub25taWNyb3NvZnQuY29tIiwidXBuIjoiYW50b25Ad2JvdWRpY2hlbGluYWdvcmEub25taWNyb3NvZnQuY29tIiwidXRpIjoiVDFmcGRkUzZjRWUxa0c0TkN5eEFBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJaNnFaZ3RvbkVJUWQxWWRPTlpDTFJ4SVJxc3FIcTY4c3haNEE5ZGZ6NTBnIn0sInhtc190Y2R0IjoxNjc0MjI4NDEyfQ.lk317_NvCketwE-fmfTAAhSqxgjWBd8onT0XnYeAzlKkT12M90be_3hVDitOWoIXZLswg0k-RI7MTdLZpFS_8PNCOq2O0LxYxYHbihUSYgtO5ZvygCgAgd1alCSNeCaLQdaREfO94dgMXQbRCRf1pZrrhWPSSABDXxNhZkbT4PsMS5ugzYyEkCmlmM60dJ12zxZQCOT-sI46N8wralBLslWsBGyJjAu4QzZ1P-YAGyLSUzM8qPdRZf4IiGJ0HrhDgESFdBGzDUjdoPc-0c6mKEDGnG_D5EvH5B-UxoZl-QUrdRRLFPrx8jTNkMfbjNAT3czuqrsAj0cSMZ3YQ0IK6Q";

	private String idToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiI2NjQwOTgyYy02ZGM4LTQxOTMtYWQ3MC03NTU2N2YyMGM1ZTMiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZDZlY2EyNzAtOGYyYy00YWU2LWFmOWEtY2IwOTc1MDI0NjlhL3YyLjAiLCJpYXQiOjE2NzUwOTQyMzUsIm5iZiI6MTY3NTA5NDIzNSwiZXhwIjoxNjc1MDk4MTM1LCJlbWFpbCI6ImFzaGVwaWxvdkBsaW5hZ29yYS5jb20iLCJvaWQiOiJlMTQ0ZWE0My0yYWFlLTQzNDQtYTZiMC0xOWU5NGRmM2RiMDkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbnRvbkB3Ym91ZGljaGVsaW5hZ29yYS5vbm1pY3Jvc29mdC5jb20iLCJwcm92X2RhdGEiOlt7IlByb3YiOiJnaXRodWIuY29tIiwiQXQiOnRydWUsIkFsdHNlY2lkIjoiMTQ5MjQ5NjMiLCJBY2Nlc3NUb2tlbiI6bnVsbH1dLCJyaCI6IjAuQVU0QWNLTHMxaXlQNWtxdm1zc0pkUUpHbWl5WVFHYkliWk5CclhCMVZuOGd4ZU9EQUZRLiIsInN1YiI6Ilo2cVpndG9uRUlRZDFZZE9OWkNMUnhJUnFzcUhxNjhzeFo0QTlkZno1MGciLCJ0aWQiOiJkNmVjYTI3MC04ZjJjLTRhZTYtYWY5YS1jYjA5NzUwMjQ2OWEiLCJ1dGkiOiJCVHV0Yk5PTXZrMllHUjRxMUFsUEFBIiwidmVyIjoiMi4wIiwiZG9tYWluX2Rpc2NyaW1pbmF0b3IiOiJBRExpblNoYXJlRG9tYWluIiwibGluc2hhcmVfYWNjZXNzIjoibGluc2hhcmUiLCJsaW5zaGFyZV9sb2NhbGUiOiJFTkdMSVNIIiwibGluc2hhcmVfcm9sZSI6IkFETUlOIn0.R_Wa0CTRmlQdTgUTrWwzOFjxlmOwym115oqVknDktOMHkVBC1a7Vubn60-r2hC-izjXvzgBIxk7g8QUrUFy_CMqXdrnLw3lMkSckAJb2wK9H8w1OoPREihxax9gPZIUcRyhIHasx5Ta9ApKBh3Q75OtyLvCVdbwiJV_vtNz2Q693tM_ASwJH3aKOKFy3CD6QIZcYi0glH6qFK4ao60IgH5p4D923vcAua6_pqkOy0X2kL0NCL-FeGCKVpj80_0gvwCsWrPucFdQ_X4j1fYVyTlCaYQqCXpJQfk3dZ8WTYMgEuzknYUDeoJD8Pw1QJifIPU9Wcn4jQCxgo8ViySE-bw";

	@Test
	@Disabled
	public void testAuthenticate() throws ParseException {
		//given jwt token
		OidcJwtAuthenticationToken token = new OidcJwtAuthenticationToken(authToken, idToken);
		JWT jwt = JWTParser.parse(authToken);

		//when
		Authentication authentication = subj.authenticate(token);

		//then
		Assertions.assertNotNull(authentication);
	}


}