UPDATE mail_content SET subject= '[( #{subject})]',
body= '<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head  data-th-replace="layout :: header"></head>
<body>
<div th:replace="layout :: email_base(upperMainContentArea = ~{::#main-content},bottomSecondaryContentArea = ~{::#secondary-content})">
  <!--/* Upper main-content*/-->
  <section id="main-content">
    <div th:replace="layout :: contentUpperSection( ~{::#section-content})">
      <div id="section-content">
        <!--/* Greetings */-->
          <th:block data-th-replace="layout :: greetings(${shareRecipient.mail})"/>
        <!--/* End of Greetings  */-->
        <!--/* Main email  message content*/-->
        <p style="font-weight:bold;font-size:15px;"  data-th-utext="#{mainTitle(${shareOwner.firstName} , ${shareOwner.lastName})}"></p>
        <p>
          <span data-th-utext="#{beginingMainMsg}"></span>
          <span data-th-utext="#{otherMsg}"></span>
          <!--/* Activation link for initialisation of the guest account */-->
          <!--<th:block data-th-replace="layout :: actionButtonLink(#{changePasswordBtn},${resetLink})"/> -->
          <br/>
        </p>
        <th:block data-th-replace="layout :: actionButtonLink(#{downloadBtn},${anonymousURL})"/></br>
        <p  data-th-utext="#{endingMainMsg}"></p>
        <!--/* End of Main email  message content*/-->
      </div><!--/* End of section-content*/-->
    </div><!--/* End of main-content container*/-->
  </section> <!--/* End of upper main-content*/-->
  <!--/* Secondary content for  bottom email section */-->
  <section id="secondary-content">
  <th:block data-th-replace="layout :: infoStandardArea(#{passwordMessageTitle},${password})"/>
  <th:block data-th-replace="layout :: infoActionLink(#{downloadLinkTit},${anonymousURL})"/>
  <th:block data-th-replace="layout :: infoDateArea(#{common.titleSharedThe},${shares[0].creationDate})"/>
  <th:block data-th-replace="layout :: infoDateArea(#{common.availableUntil},${shares[0].expirationDate})"/>
  <th:block data-th-replace="layout :: infoFileLinksListingArea(#{common.filesInShare},${shares},${anonymous})"/>

  </section>  <!--/* End of Secondary content for bottom email section */-->
</div>
</body>
</html>',
messages_french= '
	subject=LinShare Génération d''''un nouveau mot de passe
	mainTitle= Un nouveau mot de passe vous a été généré par {0} {1}.
	beginingMainMsg= Pour des raisons de sécurité un nouveau mot de passe pour accéder à votre partage a été généré.
	otherMsg= Vous pouvez de nouveau cliquer sur le boutton ci-dessous pour télécharger le partage et saisissez le nouveau mot de passe.
	endingMainMsg= Cordialement
	downloadBtn=Télécharger
	passwordMessageTitle= Voici le nouveau mot de passe:
	downloadLinkTit = lien de téléchargement:
	',
messages_english= '
	subject=LinShare New password Generation  
	mainTitle= A new password was generated by {0} {1} 
	beginingMainMsg= For a security reasons a new password was generated.
	otherMsg= You can click the button below to download the shares and enter the new generated password below.
	endingMainMsg= Regards.
	downloadBtn= Download
	passwordMessageTitle= Here is the new password:
	downloadLinkTit= Download link:
	',
messages_russian= '
	subject=LinShare New password Generation
	mainTitle= A new password was generated by {0} {1} 
	beginingMainMsg= For a security reasons a new password was generated.
	otherMsg= You can click the button below to download the shares and enter the new generated password below.
	endingMainMsg= Regards.
	downloadBtn= Download
	passwordMessageTitle= Here is the new password:
	downloadLinkTit= Download link:
	'
WHERE id= 38;