/*
 * Copyright (C) 2007-2023 - LINAGORA
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.linagora.linshare.core.domain.constants;

public enum MailActivationType {

	FILE_WARN_OWNER_BEFORE_FILE_EXPIRY,

	SHARE_NEW_SHARE_FOR_RECIPIENT,
	SHARE_NEW_SHARE_ACKNOWLEDGEMENT_FOR_SENDER,
	SHARE_FILE_DOWNLOAD_ANONYMOUS,
	SHARE_ANONYMOUS_RESET_PASSWORD,
	SHARE_FILE_DOWNLOAD_USERS,
	SHARE_FILE_SHARE_DELETED,
	SHARE_WARN_RECIPIENT_BEFORE_EXPIRY,
	SHARE_WARN_UNDOWNLOADED_FILESHARES,
	SHARE_WARN_SENDER_ABOUT_SHARE_EXPIRATION_WITHOUT_DOWNLOAD,
	SHARE_WARN_RECIPIENT_ABOUT_EXPIRED_SHARE,

	GUEST_ACCOUNT_NEW_CREATION,
	GUEST_ACCOUNT_RESET_PASSWORD_LINK,
	GUEST_WARN_GUEST_ABOUT_HIS_PASSWORD_RESET,
	GUEST_WARN_MODERATOR_ABOUT_GUEST_EXPIRATION,
	GUEST_ACCOUNT_RESET_PASSWORD_FOR_4_0,

	GUEST_MODERATOR_CREATION,
	GUEST_MODERATOR_UPDATE,
	GUEST_MODERATOR_DELETION,

	UPLOAD_REQUEST_UPLOADED_FILE,
	UPLOAD_REQUEST_UNAVAILABLE_SPACE,
	UPLOAD_REQUEST_WARN_BEFORE_EXPIRY,
	UPLOAD_REQUEST_WARN_EXPIRY,
	UPLOAD_REQUEST_CLOSED_BY_RECIPIENT,
	UPLOAD_REQUEST_FILE_DELETED_BY_RECIPIENT,

	UPLOAD_REQUEST_ACTIVATED_FOR_RECIPIENT,
	UPLOAD_REQUEST_ACTIVATED_FOR_OWNER,
	UPLOAD_REQUEST_REMINDER,
	UPLOAD_REQUEST_PASSWORD_RENEWAL,
	UPLOAD_REQUEST_CREATED,
	UPLOAD_REQUEST_CLOSED_BY_OWNER,
	UPLOAD_REQUEST_RECIPIENT_REMOVED,
	UPLOAD_REQUEST_UPDATED_SETTINGS,
	UPLOAD_REQUEST_FILE_DELETED_BY_OWNER,

	WORKGROUP_WARN_NEW_MEMBER,
	WORKGROUP_WARN_UPDATED_MEMBER,
	WORKGROUP_WARN_DELETED_MEMBER,
	WORKGROUP_WARN_DELETED_WORKGROUP,
	WORKGROUP_WARN_NEW_WORKGROUP_DOCUMENT,
	WORKGROUP_WARN_WORKGROUP_DOCUMENT_UPDATED,

	ACCOUNT_OWNER_WARN_JWT_PERMANENT_TOKEN_CREATED,
	ACCOUNT_OWNER_WARN_JWT_PERMANENT_TOKEN_DELETED,

	WORK_SPACE_WARN_NEW_MEMBER,
	WORK_SPACE_WARN_UPDATED_MEMBER,
	WORK_SPACE_WARN_DELETED_MEMBER,
	WORK_SPACE_WARN_DELETED;
}
