  -- TASK: UPGRADE_2_1_DOCUMENT_GARBAGE_COLLECTOR
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (13,
  'UNDEFINED',
  'UPGRADE_2_1_DOCUMENT_GARBAGE_COLLECTOR',
  'UPGRADE_2_1',
  null,
  null,
  13,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

    -- TASK: UPGRADE_2_1_COMPUTE_USED_SPACE_FOR_WORGROUPS
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (14,
  'UNDEFINED',
  'UPGRADE_2_1_COMPUTE_USED_SPACE_FOR_WORGROUPS',
  'UPGRADE_2_1',
  null,
  null,
  14,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);
 
 -- TASK: UPGRADE_2_1_REMOVE_ALL_THREAD_ENTRIES
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (15,
  'UNDEFINED',
  'UPGRADE_2_1_REMOVE_ALL_THREAD_ENTRIES',
  'UPGRADE_2_1',
  null,
  null,
  15,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

    -- TASK: UPGRADE_2_1_COMPUTE_CURRENT_VALUE_FOR_DOMAINS
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (16,
  'UNDEFINED',
  'UPGRADE_2_1_COMPUTE_CURRENT_VALUE_FOR_DOMAINS',
  'UPGRADE_2_1',
  null,
  'UPGRADE_2_1_COMPUTE_USED_SPACE_FOR_WORGROUPS',
  16,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

     -- TASK: UPGRADE_2_1_COMPUTE_TOP_AND_ROOT_DOMAIN_QUOTA
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (17,
  'UNDEFINED',
  'UPGRADE_2_1_COMPUTE_TOP_AND_ROOT_DOMAIN_QUOTA',
  'UPGRADE_2_1',
  null,
  'UPGRADE_2_1_COMPUTE_CURRENT_VALUE_FOR_DOMAINS',
  17,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

    -- TASK: UPGRADE_2_1_ADD_ALL_NEW_MIME_TYPE
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (18,
  'UNDEFINED',
  'UPGRADE_2_1_ADD_ALL_NEW_MIME_TYPE',
  'UPGRADE_2_1',
  null,
  null,
  18,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true); 