-- Upload Requests close expired.
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (1, 2, 10, 'subject of upload request 2', 'body of upload request 1', 'b344b5ca-d9e7-4857-b959-5e86f34a91f7', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false,'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (1, 1, '916a6e65-deb8-4120-b2ab-c64bfcbf4e02', 3, 31457280, 10485760, 'ENABLED', DATEADD(month, -2, now()), DATEADD(month, -2, now()), DATEADD(month, -2, now()), '2014-08-10 00:00:00', DATEADD(month, 1, now()), null, true, true, true, 'fr', true, null, true, true);
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (2, 2, 10, 'subject of upload request 2', 'body of upload request 2', 'f358f600-ef45-11e5-a447-5398b7a56bf6', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false,'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (2, 2, 'f3d57d10-ef45-11e5-98ad-5f9a6ac1c0ed', 3, 31457280, 10485760, 'ENABLED', DATEADD(month, -1, now()), DATEADD(month, -1, now()), DATEADD(month, -1, now()), '2014-08-10 00:00:00', DATEADD(day, -3, now()), null, true, true, true, 'fr', true, null, true, true); 
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (3, 2, 10, 'subject of upload request 3', 'body of upload request 3', 'f433a43a-ef45-11e5-a5a8-cb91b7e459b2', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false,'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (3, 3, 'f49ca05c-ef45-11e5-9c0e-f34ce5ee3ac1', 3, 31457280, 10485760, 'ENABLED', now(), now(), now(), '2014-08-10 00:00:00', '2014-09-10 00:00:00', null, true, true, true, 'fr', true, null, true, true); 

-- Upload requests enable created.
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (4, 2, 10, 'subject of upload request 4', 'body of upload request 4', 'f4f31b58-ef45-11e5-b506-c348d7a7b65a', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'CREATED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (4, 4, 'f548ac1c-ef45-11e5-a73f-4b811b25f11b', 3, 31457280, 10485760, 'CREATED', DATEADD(day, -1, now()), DATEADD(month, -2, now()), now(), DATEADD(month, 3, now()), DATEADD(month, 3, now()), null, true, true, true, 'fr', true, null, true, true);
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (5, 2, 10, 'subject of upload request 5', 'body of upload request 5', '2980a264-ef46-11e5-a0c9-0b2742279c1a', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'CREATED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (5, 5, '2a378b50-ef46-11e5-98c3-673ead758c8f', 3, 31457280, 10485760, 'CREATED', DATEADD(day, -1, now()), now(), DATEADD(month, 3, now()), DATEADD(month, 3, now()), '2014-09-10 00:00:00', null, true, true, true, 'fr', true, null, true, true);
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (6, 2, 10, 'subject of upload request 6', 'body of upload request 6', '394b8e98-ef46-11e5-800e-7f734472e0d0', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'CREATED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, pristine, enable_notification)
	VALUES (6, 6, '39a4a7e4-ef46-11e5-b1d1-e3c21cdc7a0a', 3, 31457280, 10485760, 'CREATED', DATEADD(day, -3, now()), now(), DATEADD(month, 3, now()), DATEADD(month, 3, now()), '2014-09-10 00:00:00', null, true, true, true, 'fr', true, null, true, true);

-- Upload requests notifier.
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (7, 2, 10, 'subject of upload request 4', 'body of upload request 4', 'f4j31b58-ef45-11e5-b506-c348d7a7b65a', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, notified, pristine, enable_notification)
	VALUES (7, 7, 'f547ac1c-ef45-11e5-a73f-4b811b25f11b', 3, 31457280, 10485760, 'ENABLED', DATEADD(day, -1, now()), DATEADD(month, -2, now()), now(), now(), DATEADD(month, 3, now()), null, true, true, true, 'fr', true, null, false, true, true);
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (8, 2, 10, 'subject of upload request 5', 'body of upload request 5', '29k0a264-ef46-11e5-a0c9-0b2742279c1a', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, notified, pristine, enable_notification)
	VALUES (8, 8, '2a368b50-ef46-11e5-98c3-673ead758c8f', 3, 31457280, 10485760, 'ENABLED', DATEADD(day, -1, now()), now(), now(), now(), DATEADD(month, 4, now()), null, true, true, true, 'fr', true, null, false, true, true);
INSERT INTO upload_request_group (id, domain_abstract_id, account_id, subject, body, uuid, creation_date, modification_date, max_file, max_deposit_size, max_file_size, activation_date, notification_date, expiry_date, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, enable_notification, collective, status)
	VALUES (9, 2, 10, 'subject of upload request 6', 'body of upload request 6', '39db8e98-ef46-11e5-800e-7f734472e0d0', DATEADD(month, -2, now()), DATEADD(month, -2, now()), 3, 31457280, 10485760, DATEADD(month, -2, now()), DATEADD(month, -2, now()),DATEADD(month, 1, now()), true, true, true, 'fr', true, null,true,false, 'ENABLED');
INSERT INTO upload_request (id, upload_request_group_id, uuid, max_file, max_deposit_size, max_file_size, status, activation_date, creation_date, modification_date, notification_date, expiry_date, upload_proposition_request_uuid, can_delete, can_close, can_edit_expiry_date, locale, protected_by_password, mail_message_id, notified, pristine, enable_notification)
	VALUES (9, 9, '39a407e4-ef46-11e5-b1d1-e3c21cdc7a0a', 3, 31457280, 10485760, 'ENABLED', DATEADD(day, -3, now()), now(), DATEADD(month, 3, now()), now(), DATEADD(month, 4, now()), null, true, true, true, 'fr', true, null, false, true, true);