  -- TASK: UPGRADE_2_2_MIGRATE_HISTORY_TO_MONGO_AUDIT;
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (19,
  'UNDEFINED',
  'UPGRADE_2_2_MIGRATE_UPLOAD_REQUEST_HISTORY_TO_MONGO_AUDIT',
  'UPGRADE_2_2',
  null,
  null,
  19,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

  -- TASK: UPGRADE_2_2_MIGRATE_UPLOAD_PROPOSITION_FILTER_TO_MONGO_DATABASE
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (20,
  'UNDEFINED',
  'UPGRADE_2_2_MIGRATE_UPLOAD_PROPOSITION_FILTER_TO_MONGO_DATABASE',
  'UPGRADE_2_2',
  null,
  null,
  20,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

-- TASK: UPGRADE_2_2_MIGRATE_UPLOAD_PROPOSITION_TO_MONGO_DATABASE
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
 (21,
 'UNDEFINED',
 'UPGRADE_2_2_MIGRATE_UPLOAD_PROPOSITION_TO_MONGO_DATABASE',
 'UPGRADE_2_2',
  null,
  null,
  21,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

-- TASK: UPGRADE_2_2_MIGRATE_THREAD_TO_MONGO_DATABASE
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
  (22,
  'UNDEFINED',
  'UPGRADE_2_2_MIGRATE_THREAD_TO_MONGO_DATABASE',
  'UPGRADE_2_2',
  null,
  null,
  22,
  'NEW',
  'MANDATORY',
  now(),
  now(),
  null,
  true);

-- TASK: UPGRADE_2_2_GENERATE_BASIC_STATISTICS_FROM_AUDIT_LOG_ENTRIES
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
 (23,
 'UNDEFINED',
 'UPGRADE_2_2_GENERATE_BASIC_STATISTICS_FROM_AUDIT_LOG_ENTRIES',
 'UPGRADE_2_2',
  null,
  null,
  23,
 'NEW',
 'MANDATORY',
  now(),
  now(),
  null,
  true);

-- TASK: UPGRADE_2_2_MIGRATE_WORKGROUP_AUDIT_TO_SHARED_SPACE_AUDIT
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
 (24,
 'UNDEFINED',
 'UPGRADE_2_2_MIGRATE_WORKGROUP_AUDIT_TO_SHARED_SPACE_AUDIT',
 'UPGRADE_2_2',
  null,
  null,
  24,
 'NEW',
 'MANDATORY',
  now(),
  now(),
  null,
  true);

  -- TASK: UPGRADE_2_2_MIGRATE_WORKGROUP_MEMBER_AUDIT_TO_SHARED_SPACE_MEMBER_AUDIT
INSERT INTO upgrade_task
  (id,
  uuid,
  identifier,
  task_group,
  parent_uuid,
  parent_identifier,
  task_order,
  status,
  priority,
  creation_date,
  modification_date,
  extras,
  hidden)
VALUES
 (25,
 'UNDEFINED',
 'UPGRADE_2_2_MIGRATE_WORKGROUP_MEMBER_AUDIT_TO_SHARED_SPACE_MEMBER_AUDIT',
 'UPGRADE_2_2',
  null,
  null,
  25,
 'NEW',
 'MANDATORY',
  now(),
  now(),
  null,
  true);
